### ISSUE TITLE
Project Work Flow

### ISSUE THREAD

**Issue by mady143** [viditkhemka63/Resume-screening#2]
Hi @viditkhemka63 @AnchalGupta11 @bharatbhallaCoder ,
Can any one explain the Project Workflow how it works and from which file i have to run at first..

Thanks and Regards,
Manikantha Sekhar...

**Comment by viditkhemka63** [comment]
hey @mady143 
It is  a end to end resume screening project where you can determining whether a candidate is qualified for a role based his or her education, experience, and other information captured on their resume by using Natural language processing.
  
This project is under development 

This is a MEAN stack project with python API for Natural language processing.
I will  update soon the project  workflow and  how to run in readme.md file
